### ISSUE TITLE
Lag out-of-bounds glitch

### ISSUE THREAD

**Issue by NooctisUGC** [Phil25/RTD#108]
# Bug description

Someone reported to me with video proof. They came back from AFK and rolled "LAG" which teleported them outside of the map. 

Invisibility RTD - When you jump and why in the motion of jumping you switch weapon and you lose all momentum. If you Spam scroll wheel you can basically glide 

# Report checks

> ### Please describe the bug in the section above, then post it and tick the correct boxes below.

### Required
- [x] The bug does not have an open issue.
- [x] I have described the bug.
- [ ] I mentioned whether the bug is sporadic or systematic.

### Optional
- [x] Steps to reproduce the bug are known and have been described.
- [ ] I have access to server error logs and have provided them, if any.
- [ ] I am able to check the RTD version (`sm_cvar sm_rtd2_version`) and have specified it.
- [ ] I have access to RTD default configuration file (`rtd2_perks.default.cfg`) and can confirm it's the one bundled with plugin release archive.
- [ ] I have access to RTD custom configurati

on file (`rtd2_perks.custom.cfg` or other) and have attached it to this issue.
- [ ] The issue is related to a particular perk, which has been specified by a label.

https://github.com/Phil25/RTD/assets/165837017/bce39d26-3a67-4ca1-916b-5ab71bbb8b7f

https://github.com/Phil25/RTD/assets/165837017/0a33cff4-512a-41ec-9198-cc3afa5b590e

**Comment by NooctisUGC** [comment]
The RTD version is the latest one. I believe you worked with @wheretf2 on it.

 UGC Staff - Noctis

**Comment by Phil25** [comment]
I'm aware of the weapon switching thing during Invisibility. It's not intentional but it's a result of another approach to turn a player invisible which is easier for me to work with at the cost of forfeiting a lot of control over the effect. Having said that, I'm not seeing any exploit potential when it comes to this, and since it's a result of an explicit player action (i.e. not random or a side effect of something basic like walking), I'm not looking to fix it, as that would likely mean reimplementing the whole thing again.

As for the Lag issue, I did have another report when a player got teleported slightly into a wall from which they were unable to move (which is weird because Lag doesn't teleport the player to coordinates they haven't been to before, I think it might be either a result of actual latency or some floating point error when the perk saves coordinates). Since this seems to be an edge case, I could add the unstuck prevention when the perk ends, similar to what Tiny Mann has.

**Comment by Phil25** [comment]
Fixed in [2.5.5](https://github.com/Phil25/RTD/releases/tag/2.5.5).

I also renamed this issue for clarity that only the Lag glitch was addressed.
