### ISSUE TITLE
Missing CFG file?

### ISSUE THREAD

**Issue by kp9589kp** [Phil25/RTD#110]
im trying to change the duration of some perks it says to change them in rtd2_perks.custom.cfg but i dont have that cfg? its not in the Zip when downloaded either i just redownloaded to see if i just forgot to transfer it when i originally downloaded and added to server 2 weeks ago.

**Comment by Phil25** [comment]
`rtd2_perks.custom.cfg` is for you to create. It's not included in the release so that people could drop the entire unpacked archive into the server files without worrying about overriding custom settings.

Create a text file named `rtd2_perks.custom.cfg` alongside the default config and follow the instructions [here](https://github.com/Phil25/RTD/wiki/customizing-perks) to customize perk times.

Here's an example of setting `Spawn Sentry` to last 60 seconds:
```cfg
"Effects"
{
	"spawnsentry"
	{
		"time"	"60"
	}
}
```

**Comment by kp9589kp** [comment]
oh alright thank you, i may have missed this reading through as well, is there a way to change all of the default time from 24 seconds or am i only able to change them each by creating that cfg file?

**Comment by Phil25** [comment]
No worries, take a look at [ConVars](https://github.com/Phil25/RTD/wiki/convars). You can change the default perk time by setting `sm_rtd2_duration` to your custom amount.

The config is there to fine tune stuff per perk, but by default, the perk time is that ConVar's value. However, some perks do override their duration explicitly so won't be affected (currently, that's **Timebomb**, **Fire Timebomb** and **Paranoia**). To change the time of those perks, use the custom config and set their `time` to `0` for them to default to the ConVar, or just provide the custom one from the config.

**Comment by kp9589kp** [comment]
Ahh okay i just misinterpreted the description for sm_rtd2_duration. thank you!
