### ISSUE TITLE
tiny mann is broken

### ISSUE THREAD

**Issue by minecraft420github12123** [Phil25/RTD#57]
if a player rolls tiny mann then runs into the enemy spawn door while its open they can enter it 

![20230408023254_1](https://user-images.githubusercontent.com/68617429/230708072-22fada16-ba1b-4b72-ab60-3034bdc0757e.jpg)

**Comment by Blueberryy** [comment]
valve pls fix

**Comment by flleeppyy** [comment]
Pretty sure that's intended and funny.
even if an enemy did get in your spawn, they'd be dead instantly unless your team decides to be friendly.

I do believe it should be an option to allow or disallow playered entering the enemys spawn

**Comment by AverageJuliet** [comment]
if its intended then oh my god is it broken lol

**Comment by Phil25** [comment]
Version 2.4.0 attempted a naive fix by increasing the default scale from 15% to 35% (added speed boost to compensate). This is the bare minimum not to get into BLU spawn on Dustbowl first.

I'm gonna close the issue for now, but since this is hugely map dependent, feel free to reopen if you find a map on which this happens still. If there's a case I'll consider implementing some more complex mechanics for this, but checking whether a player is in another's spawn is a complicated issue IIRC.
