### ISSUE TITLE
Forced Taunt does not account for if the user is either already taunting or taunts before the next forced taunt.

### ISSUE THREAD

**Issue by ghost** [Phil25/RTD#61]
I noticed that whenever I used the bumper car taunt in TF2, Forced Taunts did not work (the user can essentially skip any of the forced taunts they wish until the timer runs out.

In forcedtaunt.sp there is no check for this, and I am not fluent in any ways of making mods for any source games, neither am I fluent in C (beginner at C, only 1 month experience in low-level programming), but I can still see from variable names and others that no such check for this exists. Instead, the mod assumes that the taunt you are in was made by itself with no way to keep track of the taunts that itself created.

Since I'm not experienced in C or source mods, I can only give suggestions or pseudocode with fake variable names to get someone who does know an idea.

1. Either the mod keeps track of the taunts it made in order (potentially memory intensive if the owner sets the timer to a high amount and is lazy coding as the code would also need to keep track of the timing for each taunt to prevent the user from fooling the system with the same taunt)
2. Prevent the user from taunting by themselves while the client is under the spell of the Forced Taunt perk.

**Comment by Phil25** [comment]
To be honest, I quite like this circumvention. It does what the perk's name is -- forces you to taunt, even if the taunt is by your own choosing.

I'm going to close this issue because of this reasoning. Feel free to reopen if you disagree or have an idea how to address this, I wouldn't go for "breaking" players out of their taunt to force another.
